name: Docker Image CI

on:
  push:
    branches: [ master, actions ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build $PWD --file Dockerfile --tag savvily-book-generator
    - name: Create test renders
      run: ./convert.sh -a
